export const menuList = [
  {
    id: 1,
    name: "Biryani",
    img: "https://st.depositphotos.com/3147737/4962/i/600/depositphotos_49622201-stock-photo-hyderabadi-biryani-a-popular-chicken.jpg",
    isVeg: false,
    price: "250",
    snack: false,
    isDrink: false,
    isIndian: true,
    isNonVeg: true,
    hasButter: false,
    hasCheese: false,
    isAmerican: false,
  },
  {
    id: 2,
    name: "Butter Chicken",
    img: "https://images.immediate.co.uk/production/volatile/sites/30/2021/02/butter-chicken-ac2ff98.jpg",
    isVeg: false,
    isNonVeg: true,
    isDrink: false,
    isAmerican: false,
    isIndian: true,
    price: "350",
    snack: false,

    hasButter: true,
    hasCheese: true,
  },
  {
    id: 3,
    name: "Idli",
    isDrink: false,
    isAmerican: false,
    isIndian: true,
    img: "https://www.thespruceeats.com/thmb/A_g1pdGtPZBJyJ9ycu18iDzegL4=/1887x1415/smart/filters:no_upscale()/idli-56a510b63df78cf772862c34.jpg",
    isVeg: true,
    price: "50",
    hasButter: false,
    hasCheese: false,
  },
  {
    id: 4,
    name: "burger",
    price: "150",
    snack: true,
    isDrink: false,
    isAmerican: true,

    img: "https://imagesvc.meredithcorp.io/v3/jumpstartpure/image?url=https://static.onecms.io/wp-content/uploads/sites/19/2005/06/22/429048911_6152425885001_6152427053001-vs.jpg&w=1280&h=720&q=90&c=cc",
    isVeg: true,
    hasButter: false,
    hasCheese: true,
  },
  {
    id: 5,
    name: "Dosa",
    isDrink: false,
    isAmerican: false,
    isIndian: true,
    img: "https://www.archanaskitchen.com/images/archanaskitchen/0-Archanas-Kitchen-Recipes/2019/Id_Fresh_Masala_Dosa_Recipe_With_Sambar_and_Chutney_2.jpg",
    isVeg: true,
    price: "50",
    snack: false,

    hasButter: true,
    hasCheese: true,
  },
  {
    id: 6,
    name: "Samosa",
    img: "https://www.simplyrecipes.com/thmb/UzO3UxgjYRECShzMe4eIliy4gis=/2000x1333/filters:fill(auto,1)/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2019__12__Vegetable-Samosas-LEAD-5-502b04ead41c4c7e91e1a214f1d9d939.jpg",
    isVeg: true,
    snack: true,
    isAmerican: false,
    isIndian: true,
    price: "25",
    hasButter: false,
    hasCheese: false,
  },
  {
    id: 7,
    name: "Juice",
    img: "https://www.acouplecooks.com/wp-content/uploads/2020/07/Carrot-Juice-001.jpg",
    isVeg: true,
    price: "100",
    snack: true,
    isDrink: true,
    isAmerican: true,
    hasButter: false,
    hasCheese: false,
  },
  {
    id: 8,
    name: "Pani-Puri",
    img: "https://www.archanaskitchen.com/images/archanaskitchen/1-Author/sneha-archanaskitchen.com/Sweet__Spicy_Pineapple_Pani_Puri_Recipe__400.jpg",
    isVeg: true,
    price: "30",
    snack: true,
    isDrink: false,
    isAmerican: false,
    isIndian: true,
    hasButter: false,
    hasCheese: true,
  },
];
